DROP TABLE IF EXISTS todo CASCADE;
DROP TABLE IF EXISTS todo_list CASCADE;

CREATE TABLE todo_list (
	list_id integer generated by default as identity,
	list_name varchar(255) not null,
	primary key (list_id)
);

CREATE TABLE todo (
	todo_id integer generated by default as identity,
	todo_data varchar(255) not null,
	todo_status boolean not null,
	fk_list_id integer,
	primary key (todo_id),
	foreign key (fk_list_id) references todo_list(list_id) on delete cascade
);


